channels:
- conda-forge
dependencies:
- python=3.9.19
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.2.1
  - imbalanced-learn==0.11.0
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.13.0
name: mlflow-env
